### ISSUE TITLE
Rename belongsTo to doesBelongTo

### ISSUE THREAD

**Issue by blond** [bem-sdk/bem-entity-name#112]

**Comment by zxqfox** [comment]
Yeah, I strongly agree because we already have few methods starting with `is*` prefix: `isEqual`, `isBemEntityName`, `isSimpleMod`.

**Comment by skad0** [comment]
Why? I think it's wrong grammatically. `Belongs` is already a verb and ha`s` ending because of 3rd person. `Does` here isn't correct.

**Comment by zxqfox** [comment]
Decided to decline this change.
