### ISSUE TITLE
Entity Factory

### ISSUE THREAD

**Issue by blond** [bem-sdk/bem-entity-name#24]
I think we should use factory interface in API instead of `BemEntity` class.

**Now:**

``` js
const BemEntityPart = require('bem-entity-part');

const entity = new BemEntityPart({ block: 'button', elem: 'text' });
```

**Factory API:**

``` js
const bemEntityPart = require('bem-entity-part');

const entity = bemEntityPart({ block: 'button', elem: 'text' });
```

For example, it will allow create new instance only when necessary.

**Now:**

``` js
const BemEntityPart = require('bem-entity-part');

const entity1 = new BemEntityPart({ block: 'button', elem: 'text' }); // creates new instance
const entity2 = new BemEntityPart({ block: 'button', elem: 'text' }); // creates new instance

entity1 === entity2 // false
```

**Factory API:**

``` js
const bemEntityPart = require('bem-entity-part');

const entity1 = bemEntityPart({ block: 'button' }); // creates new instance
const entity2 = bemEntityPart({ block: 'button' }); // returns previously created instance

entity1 === entity2 // true
```

Also, we will be able to expand API when it is needed.

**Comment by Yeti-or** [comment]
seems that `isEqual` is closing this problem @blond ?

**Comment by blond** [comment]
@Yeti-or no, this issue about optimisation: we can create only one instance for uniq entity.

**Comment by Yeti-or** [comment]
so then let's add it as static field to our class ?
``` 
static uniqEntity(obj) {
return this.__store[entity.id] || (this.__store[naming.stringify(obj)] = new BemEntityName(obj));
}
```

**Comment by zxqfox** [comment]
Actually, `new BemEntityPart({ block: 'button', elem: 'text' });` will do what you let it do.

```js
$ node
> const qq = {object: 'yes'};
undefined
> function Lolka(){ return qq; }
undefined
> Lolka() === new Lolka()
true
```

Just need to make constructor a lil bit sneaky.

Btw, I'm not sure it will work if you load several `bem-entity-name`s from different modules. They will have different objects for the same entityNames.
