### ISSUE TITLE
Add typeOf method

### ISSUE THREAD

**Issue by blond** [bem-sdk/bem-entity-name#25]
We should move `typeOf` method from `bem-naming` (https://github.com/bem-sdk/bem-naming/issues/98).

**API:**

```js
const BemEntityPart = require('bem-entity-part');

BemEntityPart.typeOf({ block: 'button', elem: 'text' }); // elem
```

This method should support `BemEntityName` instances and objects with `block`, `elem`, `mod` properties.

**Comment by zxqfox** [comment]
Guess we can close this since
```
> new BemEntityName({block: 'b'}).type
'block'
```
right?
