### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by blond** [bem-sdk/bem-entity-name#5]
The BEM Entity is only be a block (with or without modifier) or element (with or without modifier). For example: 

```js
{ block: 'button', mods: { disabled: true } } // BEMJSON or deps format

// It means button + its modifier
```

But this package works with objects which can describe only modifier. For example: 

```js
{ block: 'button', mod: 'disabled' } // bem-naming format

// It means modifier without its block
```

I think we should rename this package to `bem-entity-part` or `bem-entity-particle`.

**Comment by Yeti-or** [comment]
```module.exports.BemEntity

**Comment by blond** [comment]
@Yeti-or these are two independent API, I see no reason to merge in one package.

For meta package we can use `bem-sdk`.

**Comment by Yeti-or** [comment]
@blond and what about putting all bem-entity formats (deps, decl, bemjson, part) to one BemEntity package?

**Comment by blond** [comment]
I think that `bem-sdk` is more suitable for all formats.

**Comment by zxqfox** [comment]
`bem-entity-chunk`?

**Comment by blond** [comment]
@zxqfox maybe this name confuse someone.

I think that `bem-entity-particle` is better.

**Comment by blond** [comment]
@tadatuta renaming is inevitable ;) It is better to choose what name do you like better.

**Comment by tadatuta** [comment]
https://lurkmore.co/Файл:Aksioma_eskobar.jpg

**Comment by blond** [comment]
We decided to rename this package to `bem-entity-name`.
