### ISSUE TITLE
Add isComplexMod

### ISSUE THREAD

**Issue by Yeti-or** [bem-sdk/bem-entity-name#81]
because `!entity.isSimpleMod` could be just block >_<

**Comment by zxqfox** [comment]
hm.

**Comment by Yeti-or** [comment]
Are you disagree?

**Comment by Yeti-or** [comment]
@zxqfox Are you disagree?

**Comment by zxqfox** [comment]
Просто есть «простые модификаторы», но нет «сложных модификаторов», и тогда непонятно что этот флаг означает. `entity.mod && !entity.isSimpleMod` кажется пока достаточно, а если делать флаг, то `isComplexMod` название не очень

**Comment by Yeti-or** [comment]
Okay so let's patch isSimpleMod:
```
isSimple:
block -> null
elem -> null
_mod -> true
_mod_val -> false
```

so we can distinguish ”complexMod” as: 
```
isSimple === false
```

**Comment by zxqfox** [comment]
I <3 it
